name    'justinstoller/chruby'
version '0.0.1'
source 'https://github.com/justinstoller/puppet-chruby'
author 'justinstoller'
license 'Apache License, Version 2.0'
summary 'Installs chruby'
description 'Installs chruby and gems into particular versions of Ruby (requires puppet-staging)'
project_page 'https://github.com/justinstoller/puppet-chruby'
dependency 'nanliu-staging'
